### ISSUE TITLE
CDQ#save throws an error given a created_at field that's not a DateTime

### ISSUE THREAD

**Issue by paddingtonsbear** [infinitered/cdq#87]
So I have the following entity 
```ruby
entity "Post" do
  integer32 :post_id
  integer32 :created_at 
end
```
as you can see `created_at` is not a DateTime but an integer. Every time I run the following code
```ruby
cdq.background do
  # only save the current thread's stack
  cdq.save(always_wait: true)

  # save the whole stack (optional)
  cdq.contexts.on(:main) { cdq.save }
end
```
I run into this error
```ruby
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Unacceptable
 type of value for attribute: property = "created_at"; desired type = NSNumber; given type = Time;
 value = 2015-03-25 01:38:49 +0000.'
```

Digging around I found this method in the `ContextManager`
```ruby
def set_timestamps
  now = Time.now

  current.insertedObjects.allObjects.each do |e|
    e.created_at = now if e.respond_to? :created_at=
    e.updated_at = now if e.respond_to? :updated_at=
  end

  current.updatedObjects.allObjects.each do |e|
    e.updated_at = now if e.respond_to? :updated_at=
  end
end
```
I think it would be a good idea to check the attribute type before setting `created_at` and `updated_at`, also wouldn't this always override a JSON response received from an api
```ruby
eg. 
{
  post_id: 1,
  created_at: Time.now.to_i # (Unix Time)
}
```

**Comment by kemiller** [comment]
I'm not crazy about checking attribute types every time you save an object since it adds expensive code at runtime.  respond_to? is more expensive than I'd like, while we're at it.  We should probably have little flags precomputed for the whole entity ahead of time.  But naming something with _at that isn't a datetime seems like not a great idea unless you want to make it use epoch time automatically.  Does ActiveRecord do that?   If so, then it's probably reasonable to match its behavior.  Feel free to make a pull request.  :)

**Comment by paddingtonsbear** [comment]
So you do have a point about naming something that isn't a datetime _at, thinking about it I might just switch to using `created_time` and that could represent unix/epoch time. I believe ActiveRecord timestamps are all `datetime`. Lets keep it as is, I dont mind using `created_time` to represent unix time
